# 分布式文件系统FDFS配置
 fdfs:
  so-timeout: 1500 #socket连接超时时长
  connect-timeout: 600 #连接tracker服务器超时时长
  resHost: 192.168.243.87
  storagePort: 8888
  thumbImage:  #缩略图生成参数，可选
      width:  150
      height:  150
  trackerList: #TrackerList参数,支持多个，我这里只有一个，如果有多个在下方加- x.x.x.x:port
    - 192.168.243.87:22122

# 上传文件配置
  spring:
   servlet:
    multipart:
      max-file-size: 100MB # 最大支持文件大小
      max-request-size: 100MB # 最大支持请求大小


